### ISSUE TITLE
UPDATED!!:FIXED WITH LATEST UPDATE Cinematic Video issue latest update.

### ISSUE THREAD

**Issue by kryptk2010** [CkauNui/ckau-book-addons-Cinematic-Video#4]
Since latest update 4k/cinematic videos just won't load, done complete removal and reinstall through zip and git same results on Batocera V40, was working prior to the latest theme update.

**Comment by benjdidj** [comment]
i dont know if its related but i cant use video fullscreen mode (or thumbmail console is fine).
I am on retrobat.
i put the files in
C:\RetroBat\emulationstation\.emulationstation\themes\ckau-book-addons

Thanks for the awesome mod.

**Comment by kryptk2010** [comment]
> i dont know if its related but i cant use video fullscreen mode (or thumbmail console is fine). I am on retrobat. i put the files in C:\RetroBat\emulationstation.emulationstation\themes\ckau-book-addons
> 
> Thanks for the awesome mod.

Same issue I'm guessing fullscreen videos appear like they're playing but no video shows up, I've tried manually going through the XML files to see if any errors but everything appears as if it should work. I'm at a loss with this one.

**Comment by kryptk2010** [comment]
Latest Update to CKau with regional changes fixed the videos!!
